budget_app/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budgets.urls')),
    path('register/', v.register, name='register'),
    path('', include("django.contrib.auth.urls")),
]

budgets/urls.py
from django.urls import path
from . import views

app_name = 'budgets'
urlpatterns = [
    path('', views.home, name='home'),
    path('budgets/<int:id>/', views.budgets, name='budgets'),
    path('transactions/<int:id>/', views.transactions, name='transactions'),
    path('account/<int:id>/', views.account, name='account'),
]

budgets/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Account(models.Model):
    """An Account is a bank/credit card type of account"""
    CREDIT_CARD = "CC"
    BANK_ACCOUNT = "BA"
    ACCOUNT_TYPE_CHOICES = [
        (CREDIT_CARD, "Credit Card"),
        (BANK_ACCOUNT, "Bank Account"),
    ]
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=25)
    balance = models.DecimalField(max_digits=11, decimal_places=2, default=0.00)
    type = models.CharField(max_length=2, choices=ACCOUNT_TYPE_CHOICES, default=BANK_ACCOUNT)
    
class Budget(models.Model):
    CATEGORY_CHOICES = [
        ('Rent/Mortgage', 'Rent/Mortgage'),
        ('Transportation', 'Transportation'),
        ('Food', 'Food'),
        ('Healthcare', 'Healthcare'),
        ('Debt Repayment', 'Debt Repayment'),
        ('Savings', 'Savings'),
        ('Personal Care', 'Personal Care'),
        ('Entertainment', 'Entertainment'),
        ('Clothing', 'Clothing'),
        ('Utilities', 'Utilities'),
        ('Insurance', 'Insurance'),
        ('Childcare/Children Expenses', 'Childcare/Children Expenses'),
        ('Miscellaneous', 'Miscellaneous'),
    ]
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='Miscellaneous')
    amount = models.DecimalField(max_digits=11, decimal_places=2)

class Transaction(models.Model):
    """A Transaction is a credit/debit from an account"""
    EXPENSE = 'EX'
    CREDIT = 'CR'
    #TRANSFER = 'TFR'
    TRANS_CHOICES = [
        (EXPENSE, 'Expense'),
        (CREDIT, 'Credit'),
        #(TRANSFER, 'Transfer'),
    ]

    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=50)
    transaction_date = models.DateField()
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    type = models.CharField(max_length=3, choices=TRANS_CHOICES)
    category = models.CharField(max_length=50, choices=Budget.CATEGORY_CHOICES, blank=True, null=True)
    cleared = models.BooleanField(default=False)

    @property
    def owner(self):
        return self.account.owner

budgets/forms.py
from django import forms
from django.forms import ModelForm
from . models import Account, Budget, Transaction

class AccountForm(ModelForm):
    class Meta:
        model = Account
        fields = ["nickname", "type"]

class TransactionForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ["transaction_date", "account", "type", "text", "amount", "category"]

class BudgetForm(ModelForm):
    class Meta:
        model = Budget
        fields = ['amount', 'category']

budgets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.core.paginator import  Paginator
from . models import Account, Budget, Transaction
from . forms import AccountForm, BudgetForm, TransactionForm
from . helper import *

# Create your views here.
@login_required
def home(request):
    """"
    Home Page for Budget App:
    View Accounts, View Budget Snapshot, Create New Account
    """
    context = {}
    print(request.POST)

    if request.method == "POST":
        #Create a new account with NewAcct submission and redirect to home page
        if 'NewAcct' in request.POST:
            form = AccountForm(data=request.POST)
            if form.is_valid():
                add_account(form, request.user)
                return redirect('/')

    #Get information for navbar
    accounts = Account.objects.filter(owner=request.user).order_by('nickname')
    context['accounts'] = accounts

    #Get information for displaying current accounts
    context['bank_accts'] = accounts.filter(type='BA').order_by('nickname')
    context['credit_accts'] = accounts.filter(type='CC').order_by('nickname')
    context['types'] = sorted(Account.ACCOUNT_TYPE_CHOICES)

    #Get information for displaying budget snapshot
    user_budgets = Budget.objects.filter(owner=request.user.id).order_by('category')
    sum_of_user_budgets =  get_budget_mtd_information(user_budgets, request.user)
    context['sum_of_user_budgets'] = sum_of_user_budgets
    
    return render(request, 'budgets/home.html', context)


@login_required
def account(request, id):
    """
    Account ID's Page: 
    Delete Account, Add New Transaction, Delete Transaction
    """
    account = get_object_or_404(Account, id=id)
    context = {}
    print(request.POST)

    #Verify the account belongs to authenticated user
    if account.owner != request.user:
        raise Http404

    if request.method == "POST":
        #Delete Account and redirect to home page
        if 'DelAcct' in request.POST:
            account.delete()
            return redirect('/')

        #Create a new transaction with NewTrans submission and return to account page
        elif 'NewTrans' in request.POST:
            form = TransactionForm(data=request.POST)
            if form.is_valid():
                new_transaction = form.save(commit=False)
                update_balance(new_transaction)
                new_transaction.save()
            return redirect('/account/'+ str(id))

        #Delete selected transaction with DelTrans submission and return to account page
        elif 'DelTrans' in request.POST:
            transaction_pk = request.POST.get('DelTrans')
            delete_transaction(transaction_pk)
            return redirect('/account/'+ str(id))


    #Get information for navbar and form submission
    context["accounts"] = Account.objects.filter(owner=request.user).order_by('nickname')

    #Get information for transaction list
    transactions = Transaction.objects.filter(account=id).order_by('-transaction_date', '-date_added')
    context["categories"] = sorted(Budget.CATEGORY_CHOICES)
    context["type_list"] = sorted(Transaction.TRANS_CHOICES)
    context["account"] = account
    context['transactions'] = transactions

    #paginator
    paginator = Paginator(transactions, 15)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context["page_obj"] = page_obj

    return render(request, 'budgets/account.html', context)


@login_required
def transactions(request, id):
    """
    User Transaction Page: 
    Add New Transaction, Delete Transaction
    """
    context = {}
    print(request.POST)
    
    #Verify the transaction page belongs to authenticated user
    if id != request.user.id:
        raise Http404

    if request.method == "POST":
        #Create a new transaction with NewTrans submission and return to transaction page
        if 'NewTrans' in request.POST:
            form = TransactionForm(data=request.POST)
            if form.is_valid():
                new_transaction = form.save(commit=False)
                update_balance(new_transaction)
                new_transaction.save()

        #Delete selected transaction with DelTrans submission and return to transaction page       
        elif 'DelTrans' in request.POST:
            transaction_pk = request.POST.get('DelTrans')
            delete_transaction(transaction_pk)
    
    #find all transactions linked to user
    accounts = Account.objects.filter(owner=id).order_by('nickname')
    user_transactions = Transaction.objects.filter(account__owner=id).order_by('-transaction_date', '-date_added')
    context["transactions"] = user_transactions

    #paginator
    paginator = Paginator(user_transactions, 15)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context["page_obj"] = page_obj

    #Get information for navbar and form submission
    context["accounts"] = accounts

    #Get information for form submission 
    context["categories"] = sorted(Budget.CATEGORY_CHOICES)
    context["type_list"] = sorted(Transaction.TRANS_CHOICES)

    return render(request, 'budgets/transactions.html', context)


@login_required
def budgets(request, id):
    """
    User Bugget Page: 
    Add New Budget, View Budget Status
    """
    context = {}
    print(request.POST)

    if id != request.user.id:
        raise Http404

    if request.method == "POST":
        if 'AddBudget' in request.POST:
            form = BudgetForm(data=request.POST)
            if form.is_valid():
                add_budget(form, request.user)
   
        elif 'DeleteBudget' in request.POST:
            budget_pk = request.POST.get('DeleteBudget')
            delete_budget(budget_pk)

    # get a list of categories user does not have budgets set up for
    all_categories =  set([choice[0] for choice in Budget.CATEGORY_CHOICES])
    user_budgets = Budget.objects.filter(owner=request.user.id).order_by('category')
    categories_with_budget = sorted(set(user_budgets.values_list('category', flat=True)))
    categories_without_budget = list(all_categories.difference(categories_with_budget))
    context['categories_without_budget'] = sorted(categories_without_budget)

    #get details for user's month to dat budget status
    sum_of_user_budgets =  get_budget_mtd_information(user_budgets, request.user)
    context['sum_of_user_budgets'] = sum_of_user_budgets

    #Get information for navbar 
    context['accounts'] = Account.objects.filter(owner=request.user).order_by('nickname')

    return render(request, 'budgets/budgets.html', context)

budgets/templates/budgets/account.html
{% extends 'budgets/base.html' %}
{% load humanize %}

{% block title %}
BudgetApp - {{ account.nickname }} Account
{% endblock %}

{% block content %}

<h1>
    <span>{{ account.nickname }}</span>
    <form method="POST">
        {% csrf_token %} 
        <button type="submit" class="btn btn-outline-danger float-right" name="DelAcct" value="{{ account.id }}">Delete Account</button>
    </form>
</h1>

<div>
    <h3 style="color: {% if account.balance < 0 %} red {% else %} #00C200 {% endif %};">
    Current Balance: ${{ account.balance|intcomma }}
    </h3>
</div>

<hr/>

<p>Add a new transaction:</p> 
<div>
    {% include "budgets/new_transaction.html" with accounts=accounts type_list=type_list categories=categories default_account_id=account.id %}
</div>

<hr/>

<div>
    {% include "budgets/list_transactions.html" with page_obj=page_obj transaction=transaction page="/account/{{account.id}}/" %}
</div>

<div>
    {% include "budgets/pagination.html" with page_obj=page_obj %}
</div>

{% endblock %}

budgets/templates/budgets/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <a class="navbar-brand" href={% url 'budgets:home' %}>
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house" >
          <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
        </svg>
         BudgetApp
      </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarNavDropdown">

          <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="false">
                  Accounts
                </a>
                    <div class="dropdown-menu">
                        {% for account in accounts %}
                            <a class="dropdown-item" href={% url 'budgets:account' id=account.id %}>{{ account.nickname }}</a>
                        {% empty %}
                            <p>No accounts available</p>
                        {% endfor %}
                    </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={% url 'budgets:transactions' id=user.id %}>Transactions</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'budgets:budgets' id=user.id %}>Budget</a>
            </li>
          </ul>
        </div>
        <ul class="nav-item my-2 my-sm-0">
          <a class="nav-link" href="/logout">Logout</a>   
        </ul>


        {% endif %}

    </nav>

    <div id="content" name="content", class="main">
        <div class="d-flex justify-content-start">
            <div class="col-12">
                <div class="pt-3">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

budgets/templates/budgets/budgets.html
{% extends 'budgets/base.html' %}
{% load humanize %}

{% block title %}
BudgetApp - Budget
{% endblock %}

{% block content %}

<div class="container-fluid">
    <p>Add a new budget</p>
    <div class="row">
        <div class="col-lg">
            <form method="POST" action={% url 'budgets:budgets' id=user.id %}>
                {% csrf_token %}
                <div class="form-row">
                <div class="col-md-6">
                    <div class="input-group is-invalid">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="validatedInputGroupSelect_category">Category</label>
                    </div>
                    <select class="custom-select" id="validatedInputGroupSelect_category" name="category" id="category">
                        <option value="">Choose...</option>
                        {% for category in categories_without_budget %}
                            <option value='{{ category }}'>{{ category }}</option>
                        {% endfor %}
                    </select>
                    </div>
                </div>
                    <div class="col">
                        <input type="number" class="form-control" placeholder="Amount" id="amount" name="amount" step="0.01" min="-999999999.99" max="999999999.99" required="required">
                    </div>
                    <div class="col"> 
                        <button type="submit" class="btn btn-outline-primary" name="AddBudget">Save</button>
                    </div>
                </div>
            </form>

            <hr/>
            <p>Budget: {% now "F Y" %} </p>
            {% include "budgets/list_budget.html" with sum_of_user_budgets=sum_of_user_budgets %}
        </div>


        <div class="col-md">
            
        </div>
    </div>
</div>

{% endblock %}

budgets/templates/budgets/home.html
{% extends 'budgets/base.html' %}
{% load humanize %}

{% block title %}
BudgetApp
{% endblock %}

{% block content %}

<div>
    <h1>Welcome, {{ user }}</h1>
</div>

<div class='container-flud'>

  <div class="row">
    <div class="col-md-6">
      <h4>Current Accounts</h4>

      <hr/>
      <table class="table table-hover table-sm">

        {% if not bank_accts and not credit_accts %}
          <p>Add your first account below to get started.</p>
        {% else %}
          {% if bank_accts %}
            <thead class="thead-dark">
              <tr>
                <th scope="col" class="col-md-3">Bank Account</th>
                <th scope="col" class="col-md-3 text-right">Balance</th>
              </tr>
            </thead>
            <tbody>
              {% include "budgets/list_account.html" with accounts=bank_accts %}
          {% endif %}

          {% if credit_accts %}
              <thead class="thead-dark">
              <tr>
                <th scope="col">Credit Card</th>
                <th scope="col" class="text-right">Balance</th>
              </tr>
              </thead>
              {% include "budgets/list_account.html" with accounts=credit_accts %}
            </tbody>
          {% endif %}
        {% endif %}
      </table>


      <p>Add a new account:</p> 
      <form method="POST" action={% url 'budgets:home' %}>
          {% csrf_token %} 
          <div class="form-row">
            <div class="col-md-5">
              <input type="text" class="form-control" placeholder="Account Nickname" id="nickname" name="nickname" maxlength="25" required="required">
            </div>

            <div class="col-md-5">
              <div class="input-group is-invalid">
                <div class="input-group-prepend">
                  <label class="input-group-text" for="validatedInputGroupSelect_type" >Options</label>
                </div>
                <select class="custom-select" id="validatedInputGroupSelect_type" name="type" id="type" required>
                  <option value="">Choose...</option>
                    {% for key, type in types %}
                        <option value={{ key }}>{{ type }}</option>
                    {% endfor %}
                </select>
              </div>

            </div>
            <div class="col-md-2">
              <button type="submit" class="btn btn-outline-primary" name="NewAcct">Save</button>
            </div>
          </div>
      </form>
    </div>

    <div class="col-md-6">
      <div>
        <h4>Budget Snapshot: {% now "F Y" %} </h4>
        <hr/>
        <table class="table table-sm table-borderless">

          <tbody>
              {% for key, details in sum_of_user_budgets.items %}
                <tr>
                    <td style="vertical-align:top;" class="col-md-2"><a href={% url 'budgets:budgets' id=user.id %}>{{ key.category }}<a></td>
                    <td class="col-md-10">
                        <div class="progress">
                            <div class="progress-bar bg-info" role="progressbar" style="width: {{ details.progress }}%;" aria-valuenow="{{ details.mtd }}" aria-valuemin="0" aria-valuemax="{{ key.amount }}">
                              {{ details.progress}}%
                            </div>
                        </div>
                        <small id="progressInfo" class="form-text text-muted">
                          ${{ details.mtd|intcomma }} of ${{ key.amount|intcomma }}
                        </small>
                    </td>
                </tr>
                    {% empty %}
                <tr>
                    <td colspan="2">Set up your first budget category <a href={% url 'budgets:budgets' id=user.id %}>here.</a></td>
                </tr>
              {% endfor %}
          </tbody>
      </table>
        
      </div>
    </div

  </div>

</div>
{% endblock %}

budgets/templates/budgets/list_account.html
{% load humanize%}

{% for account in accounts %}
  <tr class='clickable' onclick="window.location='{% url 'budgets:account' id=account.id %}'">
      <td>{{ account.nickname }}</td>
      {% if account.balance < 0 %}
        <td class='text-right' style="color: red;">
          ${{ account.balance|intcomma }}
        </td>
      {% else %}
        <td class='text-right' style="color: #00C200;">
          ${{ account.balance|intcomma }}
        </td>
      {% endif %}
  </tr>
{% endfor %}

budgets/templates/budgets/list_budget.html
{% load humanize %}
<div>
    <table class="table table-sm table-borderless">
        <thead class="thead-dark">
            <tr>
            <th scope="col" class="col-md-3">Category</th>
            <th scope="col" class="col-md-2 text-right">Budget</th>
            <th scope="col" class="col-md-2 text-right">MTD</th>
            <th scope="col" class="col-md-2 text-right">Balance</th>
            <th scope="col" class="col-md-3 text-center">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for key, details in sum_of_user_budgets.items %}
                <tr>
                    <td style="vertical-align:middle;">{{ key.category }}</td>
                    <td class="text-right" style="vertical-align:middle;">${{ key.amount|intcomma }}</td>
                    <td class="text-right" style="vertical-align:middle;">${{ details.mtd|intcomma }}</td>
                    <td class="text-right" style="vertical-align:middle;">${{ details.balance|intcomma }}</td>
                    <td class="text-right">
                        <form method="POST" action={% url 'budgets:budgets' id=user.id %}>
                            {% csrf_token %} 
                            <button type="submit" class="btn btn-outline-danger btn-sm" name="DeleteBudget" value={{ key.id }}>Delete</button>
                            </form>
                    </td>
                </tr>
                <tr>
                    <td colspan="5">
                        <div class="progress">
                            <div class="progress-bar bg-success" role="progressbar" style="width: {{ details.progress }}%;" aria-valuenow="{{ details.mtd }}" aria-valuemin="0" aria-valuemax="{{ key.amount }}"></div>
                        </div>
                        <hr/>
                    </td>
                </tr>
                    {% empty %}
                <tr>
                    <td colspan="5">Add your first budget above.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

budgets/templates/budgets/list_transactions.html
{% load humanize %}
<table class="table table-hover table-sm">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Trans Date</th>
        <th scope="col">Account</th>
        <th scope="col" class='text-center'>Transaction</th>
        <th scope="col">Description</th>
        <th scope="col" class="text-center">Amount</th>
        <th scope="col"class="text-center">Category</th>
        <th scope="col" class="text-justify">Action</th>
      </tr>
    </thead>
    <tbody>
        {% for transaction in page_obj %}
            <tr>
                <td>{{ transaction.transaction_date }}</td>
                <td><a href={% url 'budgets:account' id=transaction.account.id %}>{{ transaction.account.nickname }}</a></td>
                <td class='text-center'>{{ transaction.type }}</td>
                <td>{{ transaction.text }}</td>
                
                {% if transaction.type == 'EX' %}
                    <td class='text-right'>
                    $-{{ transaction.amount|intcomma }}
                    </td>
                {% else %}
                    <td class='text-right' style="color: #00C200;">
                    ${{ transaction.amount|intcomma }}
                    </td>
                {% endif %}

                <td class="text-center">{{ transaction.category|default:"" }}</td>
                <td class="text-justify">
                    <form method="POST">
                        {% csrf_token %} 
                        <button type="submit" class="btn btn-outline-danger btn-sm" name="DelTrans" value="{{transaction.id}}">Delete</button>
                    </form>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan='7'>Add your first transaction above.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

budgets/templates/budgets/new_transaction.html
<form method="POST">
    {% csrf_token %} 
    <div class="form-row">
        <div class="col">
            <input type="date" class="form-control" placeholder="Date" id="transaction_date" name="transaction_date" required="required">
        </div>
        <div class="col-2">
            <div class="input-group is-invalid">
            <div class="input-group-prepend">
                <label class="input-group-text" for="validatedInputGroupSelect_account" >Account</label>
            </div>
            <select class="custom-select" id="validatedInputGroupSelect_account" name="account" id="account" value="account">
                <option value="">Choose...</option>
                {% for account in accounts %}
                  {% if account.id == default_account_id %}
                    <option value="{{ account.id }}" selected>{{ account.nickname }}</option>
                  {% else %}
                    <option value={{ account.id }}>{{ account.nickname }}</option>
                  {% endif %}
                {% endfor %}
            </select>
            </div>
      </div>
        <div class="col">
            <div class="input-group is-invalid">
              <div class="input-group-prepend">
                <label class="input-group-text" for="validatedInputGroupSelect_type">Type</label>
              </div>
              <select class="custom-select" id="validatedInputGroupSelect_type" name="type" id="type" required>
                <option value="">Choose...</option>
                {% for key, type in type_list %}
                    <option value={{ key }}>{{ type }}</option>
                {% endfor %}
              </select>
            </div>
          </div>   
                  
        <div class="col">
            <input type="text" class="form-control" placeholder="Description" id="text" name="text" maxlength="50" required="required">
        </div>
        <div class="col">
            <input type="number" class="form-control" placeholder="Amount" id="amount" name="amount" step="0.01" min="-999999999.99" max="999999999.99" required="required">
        </div>

        <div class="col-2">
            <div class="input-group is-invalid">
              <div class="input-group-prepend">
                  <label class="input-group-text" for="validatedInputGroupSelect_category">Category</label>
              </div>

              <select class="custom-select" id="validatedInputGroupSelect_category" name="category" id="category">
                  <option value="">Choose...</option>
                    {% for key, category in categories %}
                        <option value='{{ key }}'>{{ category }}</option>
                    {% endfor %}
              </select>
            </div>
            <small id="category_option" class="form-text text-muted">Optional</small>
      </div>
      <div class="col">
        <button type="submit" class="btn btn-outline-primary" name="NewTrans">Save</button>
      </div>
    </div>
</form>

budgets/templates/budgets/pagination.html
<nav aria-label="...">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
        {% endif %}

        <li class="page-item active" aria-current="page">
        <span class="page-link">{{ page_obj.number }}</span>
        
        {% if page_obj.has_next %}
            </li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next</span>
            </li>
        {% endif %}
    </ul>
</nav>

budgets/templates/budgets/transactions.html
{% extends 'budgets/base.html' %}
{% load humanize %}

{% block title %}
BudgetApp - All Transactions
{% endblock %}

{% block content %}

<p>Add a new transaction:</p> 
<div>
    {% include "budgets/new_transaction.html" with accounts=accounts type_list=type_list categories=categories %}
</div>

<hr/>

<div>
    {% include "budgets/list_transactions.html" with page_obj=page_obj transaction=transaction %}
</div>

<div>
    {% include "budgets/pagination.html" with page_obj=page_obj %}
</div>

{% endblock %}